import Foundation

extension TreeSitterHighlighter {
    convenience init() {
        let languages: [(String, OpaquePointer?)] = [
            ("gap", tree_sitter_gap()),
            ("gaptst", tree_sitter_gaptst()),
            ("swift", tree_sitter_swift()),
            ("python", tree_sitter_python()),
            ("javascript", tree_sitter_javascript()),
            ("typescript", tree_sitter_typescript()),
            ("tsx", tree_sitter_tsx()),
            ("json", tree_sitter_json()),
            ("yaml", tree_sitter_yaml()),
            ("markdown", tree_sitter_markdown()),
            ("bash", tree_sitter_bash()),
            ("html", tree_sitter_html()),
            ("css", tree_sitter_css()),
            ("xml", tree_sitter_xml()),
            ("ini", tree_sitter_ini()),
            ("toml", tree_sitter_toml()),
            ("c", tree_sitter_c()),
            ("cpp", tree_sitter_cpp()),
            ("go", tree_sitter_go()),
            ("rust", tree_sitter_rust()),
            ("java", tree_sitter_java()),
            ("ruby", tree_sitter_ruby()),
            ("php", tree_sitter_php()),
            ("lua", tree_sitter_lua()),
            ("sql", tree_sitter_sql()),
            ("dockerfile", tree_sitter_dockerfile()),
            ("r", tree_sitter_r()),
            ("scala", tree_sitter_scala()),
            ("kotlin", tree_sitter_kotlin()),
            ("c_sharp", tree_sitter_c_sharp()),
            ("perl", tree_sitter_perl()),
            ("dart", tree_sitter_dart()),
            ("elixir", tree_sitter_elixir()),
            ("haskell", tree_sitter_haskell()),
            ("ocaml", tree_sitter_ocaml()),
            ("zig", tree_sitter_zig()),
            ("make", tree_sitter_make()),
            ("cmake", tree_sitter_cmake()),
            ("graphql", tree_sitter_graphql()),
            ("hcl", tree_sitter_hcl()),
            ("nix", tree_sitter_nix()),
            ("scss", tree_sitter_scss()),
            ("regex", tree_sitter_regex()),
            ("julia", tree_sitter_julia()),
            ("erlang", tree_sitter_erlang()),
            ("clojure", tree_sitter_clojure()),
            ("vim", tree_sitter_vim()),
            ("fortran", tree_sitter_fortran()),
            ("pascal", tree_sitter_pascal()),
            ("d", tree_sitter_d()),
            ("gleam", tree_sitter_gleam()),
            ("objc", tree_sitter_objc()),
            ("wat", tree_sitter_wat()),
            ("fish", tree_sitter_fish()),
            ("awk", tree_sitter_awk()),
        ]
        self.init(languages: languages, queryLoader: Self.loadQuery)
    }
}
