import SwiftUI
import Shared

struct AddCustomExtensionSheet: View {
    enum MatchMode: String, CaseIterable {
        case extensionMode = "Extension"
        case filenameMode = "Filename"
    }

    @Environment(\.dismiss) private var dismiss

    @State private var matchMode: MatchMode = .extensionMode
    @State private var extensionName = ""
    @State private var filenameName = ""
    @State private var displayName = ""
    @State private var selectedLanguage = "plaintext"
    @State private var showError = false
    @State private var errorMessage = ""
    @State private var displayNameIsAutoGenerated = true
    @State private var showOverrideConfirmation = false
    @State private var overrideBuiltInType: SupportedFileType?

    let onAdd: (CustomExtension) -> Void

    private var cleanedExtension: String {
        extensionName
            .lowercased()
            .trimmingCharacters(in: .whitespaces)
            .trimmingCharacters(in: CharacterSet(charactersIn: "."))
    }

    private var cleanedFilename: String {
        filenameName.trimmingCharacters(in: .whitespaces)
    }

    private var currentInput: String {
        matchMode == .extensionMode ? cleanedExtension : cleanedFilename
    }

    private var showsRoutingWarning: Bool {
        guard matchMode == .extensionMode else { return false }
        let ext = cleanedExtension
        return !ext.isEmpty && FileTypeRegistry.shared.fileType(for: ext) == nil
    }

    private var isValid: Bool {
        let trimmedDisplay = displayName.trimmingCharacters(in: .whitespaces)
        guard !trimmedDisplay.isEmpty else { return false }

        switch matchMode {
        case .extensionMode:
            let ext = cleanedExtension
            return !ext.isEmpty && CustomExtensionValidation.validateExtension(ext) == nil
        case .filenameMode:
            let name = cleanedFilename
            return !name.isEmpty && CustomExtensionValidation.validateFilename(name) == nil
        }
    }

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("Add Custom Mapping")
                    .font(.headline)
                Spacer()
                Button {
                    dismiss()
                } label: {
                    Image(systemName: "xmark.circle.fill")
                        .foregroundStyle(.secondary)
                }
                .buttonStyle(.plain)
            }
            .padding()

            Divider()

            Form {
                Section {
                    Picker("Match By", selection: $matchMode) {
                        ForEach(MatchMode.allCases, id: \.self) { mode in
                            Text(mode.rawValue).tag(mode)
                        }
                    }
                    .pickerStyle(.segmented)
                    .onChange(of: matchMode) {
                        displayNameIsAutoGenerated = true
                        updateAutoDisplayName()
                    }
                } header: {
                    Text("Match Type")
                }

                if matchMode == .extensionMode {
                    Section {
                        HStack {
                            Text(".")
                                .foregroundStyle(.secondary)
                            TextField("Extension (e.g. env.local)", text: $extensionName)
                                .textFieldStyle(.plain)
                                .onChange(of: extensionName) {
                                    updateAutoDisplayName()
                                }
                        }
                    } header: {
                        Text("File Extension")
                    } footer: {
                        VStack(alignment: .leading, spacing: 6) {
                            Text("Enter the extension without the leading dot. Dots are allowed (e.g. env.local).")
                                .font(.caption)
                                .foregroundStyle(.secondary)

                            if showsRoutingWarning {
                                Text("Quick Look can only use custom mappings for extensions dotViewer already ships with routing support for. Brand-new extensions may still need a dotViewer update before Finder sends them to the extension.")
                                    .font(.caption)
                                    .foregroundStyle(.orange)
                            }
                        }
                    }
                } else {
                    Section {
                        TextField("Filename (e.g. Jenkinsfile)", text: $filenameName)
                            .textFieldStyle(.plain)
                            .onChange(of: filenameName) {
                                updateAutoDisplayName()
                            }
                    } header: {
                        Text("Filename")
                    } footer: {
                        Text("Exact filename to match (e.g. Jenkinsfile, Caddyfile)")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                Section {
                    TextField("Display Name", text: $displayName)
                        .onChange(of: displayName) {
                            // If user is typing in the field and it differs from auto, stop auto-generating
                            let autoName = autoDisplayNameForCurrentInput()
                            if displayName != autoName {
                                displayNameIsAutoGenerated = false
                            }
                        }
                } header: {
                    Text("Display Name")
                } footer: {
                    Text("How this file type appears in the list")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Section {
                    Picker("Language", selection: $selectedLanguage) {
                        ForEach(HighlightLanguage.all) { lang in
                            Text(lang.pickerDisplayName).tag(lang.id)
                        }
                    }
                    .pickerStyle(.menu)
                } header: {
                    Text("Syntax Highlighting")
                } footer: {
                    Text("Choose which language to use for syntax highlighting")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
            .formStyle(.grouped)
            .scrollContentBackground(.hidden)

            Divider()

            HStack {
                Button("Cancel") { dismiss() }
                    .keyboardShortcut(.cancelAction)

                Spacer()

                Button("Add") {
                    addExtension()
                }
                .keyboardShortcut(.defaultAction)
                .disabled(!isValid)
                .buttonStyle(.borderedProminent)
            }
            .padding()
        }
        .frame(width: 420, height: 500)
        .alert("Error", isPresented: $showError) {
            Button("OK") {}
        } message: {
            Text(errorMessage)
        }
        .alert("Override Built-in Type?", isPresented: $showOverrideConfirmation) {
            Button("Cancel", role: .cancel) {}
            Button("Override") {
                commitAdd()
            }
        } message: {
            if let builtIn = overrideBuiltInType {
                Text(".\(cleanedExtension) is already mapped to \"\(builtIn.displayName)\". Your custom mapping will take priority.")
            }
        }
    }

    private func autoDisplayNameForCurrentInput() -> String {
        switch matchMode {
        case .extensionMode:
            let ext = cleanedExtension
            return ext.isEmpty ? "" : CustomExtensionValidation.autoDisplayName(from: ext)
        case .filenameMode:
            let name = cleanedFilename
            return name.isEmpty ? "" : CustomExtensionValidation.autoDisplayNameFromFilename(name)
        }
    }

    private func updateAutoDisplayName() {
        guard displayNameIsAutoGenerated else { return }
        displayName = autoDisplayNameForCurrentInput()
    }

    private func addExtension() {
        switch matchMode {
        case .extensionMode:
            addExtensionMode()
        case .filenameMode:
            addFilenameMode()
        }
    }

    private func addExtensionMode() {
        let ext = cleanedExtension

        if let validationError = CustomExtensionValidation.validateExtension(ext) {
            errorMessage = validationError
            showError = true
            return
        }

        let existingCustom = SharedSettings.shared.customExtensions
        if existingCustom.contains(where: { $0.extensionName == ext && $0.filenameMatch == nil }) {
            errorMessage = "This extension has already been added as a custom type."
            showError = true
            return
        }

        // Check for built-in override — show confirmation instead of blocking
        if let builtIn = FileTypeRegistry.shared.fileType(for: ext) {
            overrideBuiltInType = builtIn
            showOverrideConfirmation = true
            return
        }

        commitAdd()
    }

    private func addFilenameMode() {
        let name = cleanedFilename

        if let validationError = CustomExtensionValidation.validateFilename(name) {
            errorMessage = validationError
            showError = true
            return
        }

        let existingCustom = SharedSettings.shared.customExtensions
        if existingCustom.contains(where: { $0.filenameMatch?.lowercased() == name.lowercased() }) {
            errorMessage = "This filename has already been added as a custom type."
            showError = true
            return
        }

        commitAdd()
    }

    private func commitAdd() {
        let trimmedDisplay = displayName.trimmingCharacters(in: .whitespaces)

        let customExt: CustomExtension
        switch matchMode {
        case .extensionMode:
            customExt = CustomExtension(
                extensionName: cleanedExtension,
                displayName: trimmedDisplay,
                highlightLanguage: selectedLanguage
            )
        case .filenameMode:
            let name = cleanedFilename
            customExt = CustomExtension(
                extensionName: name.lowercased(),
                displayName: trimmedDisplay,
                highlightLanguage: selectedLanguage,
                filenameMatch: name
            )
        }

        onAdd(customExt)
        dismiss()
    }
}

#Preview {
    AddCustomExtensionSheet(onAdd: { _ in })
}
