#!/usr/bin/env bash
# Script: dotviewer-nuke.sh
# Description: Remove ALL dotViewer build artifacts, caches, containers, settings,
#              and installed copies. Guarantees a 100% clean slate before rebuilding.
# Usage: ./scripts/dotviewer-nuke.sh [--dry-run] [--keep-app] [--keep-settings]
#
# After nuking, rebuild with: ./scripts/dotviewer-refresh.sh

set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly APP_DIR="$ROOT_DIR/dotViewer"
readonly BUNDLE_ID="com.stianlars1.dotViewer"
readonly APP_GROUP="group.stianlars1.dotViewer.shared"

DRY_RUN=false
KEEP_APP=false
KEEP_SETTINGS=false
REMOVED_COUNT=0
REMOVED_BYTES=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Removes ALL dotViewer build output, caches, containers, preferences, and
installed app copies. After running, the next build is guaranteed clean.

Options:
  --dry-run        Show what would be removed without deleting anything
  --keep-app       Keep /Applications/dotViewer.app (only remove caches/build)
  --keep-settings  Keep user preferences and App Group settings
  -h, --help       Show this help message

What gets removed:
  - Build output:        dotViewer/build/
  - Xcode DerivedData:   ~/Library/Developer/Xcode/DerivedData/dotViewer-*
  - Installed apps:      /Applications/dotViewer.app, ~/Applications/dotViewer.app
  - Backup copies:       /Applications/dotViewer.app.bak*, ~/Applications/dotViewer.app.bak*
  - Sandbox containers:  ~/Library/Containers/com.stianlars1.dotViewer*
  - App Group:           ~/Library/Group Containers/group.stianlars1.dotViewer.shared
  - Preferences:         ~/Library/Preferences/*dotViewer* and *stianlars1*
  - Library caches:      ~/Library/Caches/com.stianlars1.dotViewer*
  - Application Support: ~/Library/Application Support/com.stianlars1.dotViewer*
  - Saved state:         ~/Library/Saved Application State/com.stianlars1.dotViewer*
  - HTTP storages:       ~/Library/HTTPStorages/com.stianlars1.dotViewer*
  - WebKit data:         ~/Library/WebKit/com.stianlars1.dotViewer*
  - Runtime caches:      /var/folders/.../C/com.stianlars1.dotViewer*
  - Thumbnail temp files: /var/folders/.../T/dotviewer-thumbnail-*
  - Crash reports:       ~/Library/Logs/DiagnosticReports/*dotViewer*
  - PluginKit:           Unregisters Quick Look extensions
  - Quick Look caches:   qlmanage -r cache
  - Generated project:   dotViewer.xcodeproj (regenerated by xcodegen)
EOF
}

log() {
  echo "[nuke] $*" >&2
}

warn() {
  echo "[nuke] ⚠ $*" >&2
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run)   DRY_RUN=true; shift ;;
      --keep-app)  KEEP_APP=true; shift ;;
      --keep-settings) KEEP_SETTINGS=true; shift ;;
      -h|--help)   usage; exit 0 ;;
      *)           log "Unknown argument: $1"; usage; exit 1 ;;
    esac
  done
}

# Remove a path (file or directory). Tracks count.
nuke_path() {
  local path="$1"
  local label="${2:-$1}"

  if [[ -e "$path" || -L "$path" ]]; then
    local size=0
    if [[ -d "$path" ]]; then
      size=$(du -sk "$path" 2>/dev/null | cut -f1 || echo 0)
    else
      size=$(stat -f%z "$path" 2>/dev/null || echo 0)
      size=$(( size / 1024 ))
    fi

    if [[ "$DRY_RUN" == true ]]; then
      log "[dry-run] Would remove: $label (${size}K)"
    else
      rm -rf "$path"
      log "rm -rf \"$path\""
      log "Removed: $label (${size}K)"
    fi
    REMOVED_COUNT=$((REMOVED_COUNT + 1))
    REMOVED_BYTES=$((REMOVED_BYTES + size))
  fi
}

# Remove paths matching a glob pattern.
nuke_glob() {
  local pattern="$1"
  local label="${2:-$1}"
  local found=false

  # Use bash globbing (nullglob-safe)
  local matches=()
  while IFS= read -r -d '' match; do
    matches+=("$match")
  done < <(find "$(dirname "$pattern")" -maxdepth 1 -name "$(basename "$pattern")" -print0 2>/dev/null || true)

  for match in "${matches[@]+"${matches[@]}"}"; do
    [[ -z "$match" ]] && continue
    nuke_path "$match" "$label: $(basename "$match")"
    found=true
  done

  if [[ "$found" == false && "$DRY_RUN" == true ]]; then
    log "[dry-run] Not found: $label"
  fi
}

kill_dotviewer_processes() {
  log "Killing any running dotViewer processes..."
  local procs=("dotViewer" "QuickLookExtension" "QuickLookThumbnailExtension" "HighlightXPC")
  for proc in "${procs[@]}"; do
    if pgrep -x "$proc" >/dev/null 2>&1; then
      if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would kill: $proc"
      else
        killall "$proc" 2>/dev/null || true
        log "Killed: $proc"
      fi
    fi
  done
}

unregister_plugins() {
  log "Unregistering Quick Look plugins..."
  local extensions=(
    "${BUNDLE_ID}.QuickLookPreview"
    "${BUNDLE_ID}.QuickLookThumbnail"
    "${BUNDLE_ID}.QuickLookExtension"
  )
  for ext in "${extensions[@]}"; do
    if pluginkit -m -i "$ext" >/dev/null 2>&1; then
      if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would unregister: $ext"
      else
        pluginkit -e ignore -i "$ext" 2>/dev/null || true
        log "Unregistered: $ext"
      fi
    fi
  done
}

reset_quicklook_caches() {
  log "Resetting Quick Look caches..."
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] Would run: qlmanage -r && qlmanage -r cache"
  else
    qlmanage -r >/dev/null 2>&1 || true
    qlmanage -r cache >/dev/null 2>&1 || true
    log "Quick Look caches reset"
  fi
}

nuke_build_output() {
  log "--- Build output ---"
  nuke_path "$APP_DIR/build" "Local build dir"
}

nuke_derived_data() {
  log "--- Xcode DerivedData ---"
  nuke_glob "$HOME/Library/Developer/Xcode/DerivedData/dotViewer-*" "DerivedData"
  nuke_glob "$HOME/Library/Developer/Xcode/Products/${BUNDLE_ID}*" "Xcode Products"
  nuke_glob "$HOME/Library/Developer/Xcode/UserData/CodingAssistant/dotViewer-*" "Xcode CodingAssistant"
}

nuke_generated_project() {
  log "--- Generated Xcode project ---"
  nuke_path "$APP_DIR/dotViewer.xcodeproj" "Generated .xcodeproj"
}

nuke_installed_apps() {
  log "--- Installed app bundles ---"

  if [[ "$KEEP_APP" == false ]]; then
    nuke_path "/Applications/dotViewer.app" "System install"
    nuke_path "$HOME/Applications/dotViewer.app" "User install"
  else
    log "Keeping installed apps (--keep-app)"
  fi

  # Always remove backups (refresh.sh creates .bak files in the install dir)
  nuke_glob "/Applications/dotViewer.app.bak*" "System backup copies"
  nuke_glob "$HOME/Applications/dotViewer.app.bak*" "User backup copies"
}

nuke_containers() {
  log "--- Sandbox containers ---"
  local containers=(
    "$HOME/Library/Containers/${BUNDLE_ID}"
    "$HOME/Library/Containers/${BUNDLE_ID}.QuickLookPreview"
    "$HOME/Library/Containers/${BUNDLE_ID}.QuickLookThumbnail"
    "$HOME/Library/Containers/${BUNDLE_ID}.QuickLookExtension"
    "$HOME/Library/Containers/${BUNDLE_ID}.HighlightXPC"
    "$HOME/Library/Containers/${BUNDLE_ID}.CopyHelper"
  )
  for container in "${containers[@]}"; do
    nuke_path "$container" "Container: $(basename "$container")"
  done

  if [[ "$KEEP_SETTINGS" == true ]]; then
    log "Keeping App Group container (--keep-settings)"
  else
    log "--- App Group container ---"
    nuke_path "$HOME/Library/Group Containers/${APP_GROUP}" "App Group"
  fi
}

nuke_preferences() {
  log "--- Preferences ---"

  if [[ "$KEEP_SETTINGS" == true ]]; then
    log "Keeping preferences (--keep-settings)"
    return
  fi

  local prefs=(
    "$HOME/Library/Preferences/${BUNDLE_ID}.plist"
    "$HOME/Library/Preferences/${APP_GROUP}.plist"
    "$HOME/Library/Preferences/group.${BUNDLE_ID}.shared.plist"
  )
  for pref in "${prefs[@]}"; do
    nuke_path "$pref" "Preferences: $(basename "$pref")"
  done

  # Kill cfprefsd to flush cached preferences from memory
  if [[ "$DRY_RUN" == false ]]; then
    killall cfprefsd 2>/dev/null || true
  fi
}

nuke_runtime_caches() {
  log "--- Runtime caches ---"

  # /var/folders caches are user-session-specific, find them dynamically
  local cache_base
  cache_base="$(getconf DARWIN_USER_CACHE_DIR 2>/dev/null || echo "")"

  if [[ -n "$cache_base" && -d "$cache_base" ]]; then
    nuke_glob "${cache_base}${BUNDLE_ID}*" "Runtime cache"
  fi

  # Temp files (thumbnail PNGs etc.)
  local temp_base
  temp_base="$(getconf DARWIN_USER_TEMP_DIR 2>/dev/null || echo "")"

  if [[ -n "$temp_base" && -d "$temp_base" ]]; then
    nuke_glob "${temp_base}${BUNDLE_ID}*" "Temp files"
    nuke_glob "${temp_base}dotviewer-thumbnail-*" "Thumbnail temp files"
  fi
}

nuke_library_data() {
  log "--- Library data ---"

  # Caches
  nuke_glob "$HOME/Library/Caches/${BUNDLE_ID}*" "Library Caches"

  # Application Support
  nuke_glob "$HOME/Library/Application Support/${BUNDLE_ID}*" "Application Support"
  nuke_path "$HOME/Library/Application Support/dotViewer" "Application Support (by name)"

  # App Group caches. Keep preferences when --keep-settings is set, but clear caches.
  nuke_path "$HOME/Library/Group Containers/${APP_GROUP}/PreviewCache" "App Group preview cache"
  nuke_path "$HOME/Library/Group Containers/${APP_GROUP}/Library/Caches" "App Group caches"

  # Saved Application State (window positions, restore state)
  nuke_glob "$HOME/Library/Saved Application State/${BUNDLE_ID}*" "Saved Application State"

  # HTTPStorages
  nuke_glob "$HOME/Library/HTTPStorages/${BUNDLE_ID}*" "HTTP Storages"

  # WebKit data (preview extension uses WKWebView-style rendering)
  nuke_glob "$HOME/Library/WebKit/${BUNDLE_ID}*" "WebKit data"
}

nuke_crash_reports() {
  log "--- Crash reports ---"
  local report_dirs=(
    "$HOME/Library/Logs/DiagnosticReports"
  )
  for dir in "${report_dirs[@]}"; do
    if [[ -d "$dir" ]]; then
      while IFS= read -r -d '' report; do
        nuke_path "$report" "Crash report: $(basename "$report")"
      done < <(find "$dir" -maxdepth 1 \( -name "*dotViewer*" -o -name "*HighlightXPC*" -o -name "*QuickLookExtension*" -o -name "*QuickLookThumbnailExtension*" \) -print0 2>/dev/null || true)
    fi
  done

  nuke_glob "$HOME/Library/Application Support/CrashReporter/dotViewer_*" "Crash metadata"
}

print_summary() {
  echo ""
  if [[ "$DRY_RUN" == true ]]; then
    log "=== DRY RUN SUMMARY ==="
    log "Would remove $REMOVED_COUNT items (~$((REMOVED_BYTES / 1024)) MB)"
    log "Run without --dry-run to actually delete."
  else
    log "=== NUKE COMPLETE ==="
    log "Removed $REMOVED_COUNT items (~$((REMOVED_BYTES / 1024)) MB)"
    log ""
    log "To rebuild from scratch:"
    log "  ./scripts/dotviewer-refresh.sh"
  fi
}

main() {
  parse_args "$@"

  if [[ "$DRY_RUN" == true ]]; then
    log "=== DRY RUN MODE (nothing will be deleted) ==="
  else
    log "=== NUKING ALL DOTVIEWER DATA ==="
    warn "This will remove ALL build artifacts, caches, containers, and settings."
    echo ""
    read -r -p "[nuke] Continue? (y/N) " confirm
    if [[ "$confirm" != [yY] ]]; then
      log "Aborted."
      exit 0
    fi
  fi

  echo ""

  # 1. Kill running processes first
  kill_dotviewer_processes

  # 2. Unregister extensions before removing the app
  unregister_plugins

  # 3. Remove all artifacts
  nuke_build_output
  nuke_derived_data
  nuke_generated_project
  nuke_installed_apps
  nuke_containers
  nuke_preferences
  nuke_library_data
  nuke_runtime_caches
  nuke_crash_reports

  # 4. Reset Quick Look caches last (after app removal)
  reset_quicklook_caches

  print_summary
}

main "$@"
